# Generated by Django 4.0.5 on 2022-06-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('food', 'food'), ('sport', 'sport'), ('adventure', 'adventure')], max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
